### ISSUE TITLE
implementation of tricore version 1.6 instructions

### ISSUE THREAD

**Issue by DarrylC03** [Cheb57/binutils-tricore#1]
Your version of objdump with the tricore extension is very handy. I noticed tricore instructions is am implementation of the earlier version 1.3.8. Are you still maintaining this and if so do you want the list of the new instructions for the tricore? I am happy to make a branch and extend the code to cover the new instructions as well.

**Comment by Cheb57** [comment]
Hello DarrylC03,

This is not my version but the one provided by HighTec when they need to
provide GPL versions of their adding for tricore arch.... it cover one
of my need targeting the old instructions set for TC1797 and TC1793 used
by my company, an automotive OEM, on some projects for carmakers.
HighTec did not release binaries in public except if you purchase one of
their debugging solution. I just noticed by clicking on their website
link into the readme that sources have been removed. Maybe you can get
the last revision if they are still using binutils for tricore by
requesting them.

About the revision of the instruction set, i don't have enough time to
meet this wish and I'm not maintaining this source. I don't want to
create a new branch on this repository but you can create you own repo
by taking the source released by HighTec and present on this repository
into the /usr/local/src directory (binutils-2.13.tar.bz2).

Regards,

Rabia Chebah.

Le 02/03/2020 à 05:06, DarrylC03 a écrit :
